<a href="https://colab.research.google.com/github/Aayushkumr/indianelection-prediction/blob/main/Sentiment_Analysis_IndianElections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
!pip install TextBlob
import plotly.graph_objects as go
import plotly.express as xp
from textblob import TextBlob

Requirement already satisfied: TextBlob in /usr/local/lib/python3.10/dist-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.10/dist-packages (from TextBlob) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->TextBlob) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->TextBlob) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->TextBlob) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk>=3.1->TextBlob) (4.66.1)

In [3]:
from google.colab import files


uploaded = files.upload()

Saving modi_reviews.csv to modi_reviews.csv

In [4]:
import io

modi = pd.read_csv(io.BytesIO(uploaded['modi_reviews.csv']))

In [5]:
uploaded = files.upload()

Saving rahul_reviews.csv to rahul_reviews.csv

In [6]:
rahul = pd.read_csv(io.BytesIO(uploaded['rahul_reviews.csv']))

In [7]:
modi.head(3)

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...

In [8]:
modi.shape

(25688, 3)

In [9]:
rahul.head(3)

,Unnamed: 0,User,Tweet
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...

In [10]:
rahul.shape

(14261, 3)

In [11]:
modi['Tweet'][0]

'@anjanaomkashyap I am seeing you as future #bjp spokesperson..\nGood luck. Anjana Om Modi oops Kashyap.\nJournalists like you changed the meaning of journalism. Janta maaf nai karege'

In [12]:
TextBlob(modi['Tweet'][0]).sentiment

Sentiment(polarity=0.35, subjectivity=0.36250000000000004)

In [13]:
TextBlob(rahul['Tweet'][0]).sentiment

Sentiment(polarity=0.21875, subjectivity=0.4017857142857143)

In [14]:
modi['Tweet'] = modi['Tweet'].astype(str)
rahul['Tweet'] = rahul['Tweet'].astype(str)

def find_polarity(review):
    return TextBlob(review).sentiment.polarity

In [15]:
modi['Polarity'] = modi['Tweet'].apply(find_polarity)
rahul['Polarity'] = rahul['Tweet'].apply(find_polarity)

In [16]:
modi

,Unnamed: 0,User,Tweet,Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542

In [17]:
rahul

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667
...,...,...,...,...
14256,14256,SunjayJK,"@quizzicalguy In this #LokSabhaElections2019, ...",0.000000
14257,14257,SunjayJK,@AnumaVidisha @RahulGandhi @ArvindKejriwal whe...,-0.500000
14258,14258,RAMANKAIRA,@sherryontopp Early morning #political move af...,0.080000
14259,14259,RAMANKAIRA,@mayankgandhi04 @mallesh_2004 Early morning #p...,0.080000
14260,14260,RAMANKAIRA,@DrKumarVishwas Early morning #political move ...,0.080000

In [18]:
rahul.head()

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667

In [19]:
modi['Label'] = np.where(modi['Polarity']>0,'positive','negative')
modi['Label'][modi['Polarity']==0]='Neutral'

rahul['Label'] = np.where(rahul['Polarity']>0,'positive','negative')
rahul['Label'][rahul['Polarity']==0]='Neutral'

<ipython-input-19-3d0c11c30ff7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modi['Label'][modi['Polarity']==0]='Neutral'
<ipython-input-19-3d0c11c30ff7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rahul['Label'][rahul['Polarity']==0]='Neutral'

In [20]:
rahul.head()

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750,positive
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000,Neutral
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000,Neutral
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000,positive
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667,negative

In [21]:
neutral_modi = modi[modi['Polarity']==0.0000]

remove_neutral_modi = modi['Polarity'].isin(neutral_modi['Polarity'])
modi.drop(modi[remove_neutral_modi].index,inplace=True)
print(neutral_modi.shape)
print(modi.shape)

(8207, 5)
(17481, 5)

In [22]:
neutral_rahul = rahul[rahul['Polarity']==0.0000]
remove_neutral_rahul = rahul['Polarity'].isin(neutral_rahul['Polarity'])
rahul.drop(rahul[remove_neutral_rahul].index,inplace=True)
print(neutral_rahul.shape)
print(rahul.shape)

(4894, 5)
(9367, 5)

In [23]:
print(modi.shape)
print(rahul.shape)

(17481, 5)
(9367, 5)

#Modi

In [24]:
np.random.seed(10)
remove_n = 8481
drop_indices = np.random.choice(modi.index,remove_n,replace=False)
df_modi = modi.drop(drop_indices)

In [25]:
np.random.seed(10)
remove_n = 367
drop_indices1 = np.random.choice(rahul.index,remove_n,replace=False)
df_rahul = rahul.drop(drop_indices1)

In [26]:
print(df_modi.shape)
print(df_rahul.shape)

(9000, 5)
(9000, 5)

#Prediction about Indian election

In [29]:
modi_count = df_modi.groupby('Label').count()
neg_modi = (modi_count['Polarity'][0] / 1000) * 100
pos_modi = (modi_count['Polarity'][1] / 1000) * 100

In [30]:
modi_count

          Unnamed: 0  User  Tweet  Polarity
Label
negative        2600  2600   2600      2600
positive        6400  6400   6400      6400

In [31]:
rahul_count = df_rahul.groupby('Label').count()
neg_rahul = (rahul_count['Polarity'][0] / 1000) * 100
pos_rahul = (rahul_count['Polarity'][1] / 1000) * 10

In [32]:
rahul_count

          Unnamed: 0  User  Tweet  Polarity
Label
negative        3039  3039   3039      3039
positive        5961  5961   5961      5961

In [33]:
politicians = ['Modi','Rahul']

neg_list = [neg_modi,neg_rahul]
pos_list = [pos_modi,neg_modi]


fig = go.Figure(
data = [
    go.Bar(name='Negative',x=politicians,y=neg_list),
    go.Bar(name='Positive',x=politicians,y=pos_list)
]
)
fig.update_layout(barmode='group')
fig.show()